services:
  frontend:
    image: ${DOCKER_IMAGE:-ghcr.io/${GITHUB_REPOSITORY}:${IMAGE_TAG:-latest}}
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: ${CONTAINER_NAME:-flight-frontend}
    restart: unless-stopped
    ports:
      - '${HOST_PORT:-3000}:80'
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    env_file:
      - .env
    networks:
      - flight-network
    labels:
      - 'com.docker.compose.project=flight-mnm'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

networks:
  flight-network:
    driver: bridge
