services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: flight-frontend-prod
    restart: unless-stopped
    ports:
      - '3000:80'
    env_file:
      - .env
    networks:
      - flight-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

networks:
  flight-network:
    driver: bridge
