services:
  frontend:
    image: ${APP_IMAGE:-ghcr.io/tuandm21/flight_fe:main-20250925}
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: flight-frontend-prod
    restart: unless-stopped
    ports:
      - '${HOST_PORT:-3000}:80'
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    env_file:
      - .env
    networks:
      - flight-shared-network
    labels:
      - 'com.docker.compose.project=flight-mnm'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

networks:
  flight-shared-network:
    external: true
    name: flight-shared-network
